try:
    number = 10+'10'
except:
    print('Exception occured !')
else:
    print('Else part got called !')
finally:
    print('Finally always gets called !')

#####################################################

try:
    number = 10+11
except:
    print('Exception occured !')
else:
    print('Else part got called !')
finally:
    print('Finally always gets called !')

#####################################################
